title: Ashfaq Nasir
description: Microsoft Certified Professional | Azure AI & Security
theme: minima

certifications:
    - name: Implement Agentic AI - Project Ready PROFICIENT
    badge_image: /assets/img/badges/agentic-ai-proficient.png
    badge_url: https://www.credly.com/badges/b43e1562-2ae7-4061-a98d-caf048566382/public_url
    - name: Build AI apps and agents with Azure - Project Ready Skilled
    badge_image: /assets/img/badges/azure-ai-apps-skilled.png
    badge_url: https://www.credly.com/badges/33ea559e-fd2a-480d-bea7-339d034d8a2a/public_url
    - name: Microsoft Fabric - Fabric IQ - Project Ready Skilled
    badge_image: /assets/img/badges/fabric-iq-skilled.png
    badge_url: https://www.credly.com/badges/f6f3a76d-0fb7-4f4b-babd-092973d8f8ef/public_url
    - name: Modernize and Optimize SOC with Microsoft Sentinel - Project Ready PROFICIENT
    badge_image: /assets/img/badges/sentinel-soc-proficient.png
    badge_url: https://www.credly.com/badges/06338d61-79e8-4dbb-b273-a5744a5b1887/public_url
